# Generated by Django 6.0.2 on 2026-04-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyInventoryApp", "0002_rename_createdat_supplier_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
